import Head from "next/head";
import Image from "next/image";
import ShippingNote from "../components/Shipping-Note";
import Hero from "../components/Hero";
import NavDesktop from "../components/Nav-desktop";
import BestSellers from "../components/Best-Sellers";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavDesktop />
        <Hero />
      </div>
      <div>
        <BestSellers />
      </div>
    </div>
  );
}
