import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import ShippingNote from "../components/Shipping-Note";
import Hero from "../components/Nav/Hero";
import NavHomepage from "../components/Nav/Nav-homepage";
import BestSellers from "../components/Carousels/Best-Sellers";
import BestSellersMobile from "../components/Carousels/Best-Sellers-Mobile";
import Crafted from "../components/HomePage/Crafted";
import ColloectionSec from "../components/HomePage/Collection-Sec";
import Sustainability from "../components/HomePage/Sustain";
import Blog from "../components/Blog/Blog";
import BlogCarousel from "../components/Blog/Blog-carousel";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavHomepage />
        <Hero />
      </div>
      <div>
        <BestSellers />
        <BestSellersMobile />
      </div>
      <div>
        <Crafted />
      </div>
      <div>
        <Link href="/Cups-Collection">Cups</Link>
      </div>
      <div className="lg:w-2/3 md:w-10/12 sm:w-11/12 mx-auto mb-40">
        <h2 className="text-center font-bold text-text lg:text-5xl md:text-4xl sm:text-3xl antialiased">
          Bridging the gap between <i className="font-medium">makers</i> and
          users by sharing the
          <i className="font-medium"> stories</i> and
          <i className="font-medium"> traditions</i> behind the products we use.
        </h2>
      </div>
      <div>
        <ColloectionSec />
      </div>
      <div>
        <Sustainability />
      </div>
      <div>
        <Blog />
        <BlogCarousel />
      </div>
    </div>
  );
}
